---
- name: "Creating SSH key for service user suser in ~suser/.ssh/id_rsa."
  user:
    name: suser
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    password_lock: yes
